# Generated by Django 5.2.17 on 2026-09-14 15:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام مناسبت')),
                ('icon', models.CharField(default='🎁', max_length=8, verbose_name='آیکن (ایموجی)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مناسبت هدیه',
                'verbose_name_plural': 'مناسبت\u200cهای هدیه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=160, verbose_name='نام هدیه')),
                ('given_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ هدیه')),
                ('giver', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='هدیه\u200cدهنده')),
                ('receiver', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='هدیه\u200cگیرنده')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('currency', models.CharField(blank=True, default='', max_length=12, verbose_name='واحد پول')),
                ('price_band', models.CharField(blank=True, choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا')], default='', max_length=10, verbose_name='رنج قیمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('reaction', models.CharField(blank=True, max_length=255, verbose_name='واکنش هدیه\u200cگیرنده')),
                ('photo', models.ImageField(blank=True, upload_to='gifts/', verbose_name='عکس هدیه')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='هدیه\u200cی خاص (نمایش در خاطره\u200cها)')),
                ('recorded_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='ثبت\u200cکننده')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='content.memory', verbose_name='خاطره\u200cی مرتبط')),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='gifts.giftoccasion', verbose_name='مناسبت')),
            ],
            options={
                'verbose_name': 'هدیه',
                'verbose_name_plural': '۲۶) دفتر هدیه\u200cها',
                'ordering': ['-given_on', '-created_at'],
                'indexes': [models.Index(fields=['giver', 'given_on'], name='gifts_gift_giver_003a3f_idx'), models.Index(fields=['-given_on'], name='gifts_gift_given_o_f22767_idx')],
            },
        ),
    ]
