# Generated by Django 5.2.17 on 2026-09-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='کاربر')),
                ('mode', models.CharField(choices=[('flash', 'فلش\u200cکارت'), ('quiz', 'کوییز')], default='flash', max_length=12, verbose_name='حالت')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='درست')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='کل')),
            ],
            options={
                'verbose_name': 'تمرین زبان',
                'verbose_name_plural': 'تمرین\u200cهای زبان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام دسته')),
                ('icon', models.CharField(default='💬', max_length=8, verbose_name='آیکن (ایموجی)')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cی زبان',
                'verbose_name_plural': 'دسته\u200cهای زبان',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, unique=True, verbose_name='کاربر')),
                ('learned_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کلمات یادگرفته')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='روزهای پیوسته')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='بهترین streak')),
                ('last_practiced', models.DateField(blank=True, null=True, verbose_name='آخرین تمرین')),
                ('learned_ids', models.JSONField(blank=True, default=list, verbose_name='شناسه\u200cی کلمات یادگرفته\u200cشده')),
            ],
            options={
                'verbose_name': 'پیشرفت زبان',
                'verbose_name_plural': 'پیشرفت زبان',
            },
        ),
        migrations.CreateModel(
            name='LanguageQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('question', models.CharField(max_length=255, verbose_name='سؤال')),
                ('options', models.JSONField(blank=True, default=list, help_text='مثال: ["سلام", "خداحافظ", "ممنون"]', verbose_name='گزینه\u200cها')),
                ('answer', models.CharField(max_length=200, verbose_name='پاسخ درست')),
                ('fun_feedback', models.CharField(blank=True, max_length=200, verbose_name='بازخورد بامزه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='language.languagecategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'سؤال کوییز زبان',
                'verbose_name_plural': 'سؤال\u200cهای کوییز زبان',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LanguageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('word', 'کلمه'), ('idiom', 'اصطلاح و ضرب\u200cالمثل')], default='word', max_length=10, verbose_name='نوع')),
                ('text', models.CharField(max_length=200, verbose_name='متن اصلی')),
                ('language', models.CharField(choices=[('mzn', 'مازندرانی'), ('tr', 'ترکی'), ('fa', 'فارسی'), ('en', 'English')], default='mzn', max_length=4, verbose_name='زبان اصلی')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='مثال: {"fa": "سلام", "tr": "Merhaba"}', verbose_name='معادل\u200cها')),
                ('literal_meaning', models.CharField(blank=True, max_length=255, verbose_name='معنی تحت\u200cاللفظی (برای اصطلاح)')),
                ('real_meaning', models.CharField(blank=True, max_length=255, verbose_name='معنی واقعی')),
                ('example', models.CharField(blank=True, max_length=255, verbose_name='مثال در جمله')),
                ('pronunciation', models.FileField(blank=True, upload_to='language/audio/', verbose_name='فایل تلفظ')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='افزوده\u200cشده توسط')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='language.languagecategory', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'کلمه یا اصطلاح',
                'verbose_name_plural': '۲۹) دیکشنری پل زبان',
                'ordering': ['category__order', '-created_at'],
                'indexes': [models.Index(fields=['kind', 'language'], name='language_la_kind_d3fdb8_idx')],
            },
        ),
    ]
