# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='توکن')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='دستگاه')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('vault_until', models.DateTimeField(blank=True, null=True, verbose_name='اعتبار صندوقچه')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بازدید')),
            ],
            options={
                'verbose_name': 'نشست دستگاه',
                'verbose_name_plural': 'نشست\u200cهای دستگاه',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='UnlockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تلاش ورود',
                'verbose_name_plural': 'تلاش\u200cهای ورود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('daughter_name', models.CharField(default='مریم', max_length=60, verbose_name='اسم دخترم')),
                ('daughter_nickname', models.CharField(default='دخترم', max_length=60, verbose_name='اسم نازی')),
                ('daddy_name', models.CharField(default='بابا', max_length=60, verbose_name='اسم بابا')),
                ('daughter_birthday', models.DateField(blank=True, null=True, verbose_name='تولد دخترم')),
                ('relationship_start', models.DateField(blank=True, null=True, verbose_name='روز شروع ما')),
                ('anniversary', models.DateField(blank=True, null=True, verbose_name='سالگرد ما')),
                ('next_meeting', models.DateTimeField(blank=True, null=True, verbose_name='دیدار بعدی')),
                ('daddy_city', models.CharField(default='تهران', max_length=60, verbose_name='شهر بابا')),
                ('daddy_lat', models.FloatField(default=35.6892, verbose_name='عرض جغرافیایی بابا')),
                ('daddy_lng', models.FloatField(default=51.389, verbose_name='طول جغرافیایی بابا')),
                ('daddy_timezone', models.CharField(default='Asia/Tehran', max_length=60, verbose_name='منطقه زمانی بابا')),
                ('daughter_city', models.CharField(default='استانبول', max_length=60, verbose_name='شهر دخترم')),
                ('daughter_lat', models.FloatField(default=41.0082, verbose_name='عرض جغرافیایی دخترم')),
                ('daughter_lng', models.FloatField(default=28.9784, verbose_name='طول جغرافیایی دخترم')),
                ('daughter_timezone', models.CharField(default='Europe/Istanbul', max_length=60, verbose_name='منطقه زمانی دخترم')),
                ('passcode_hash', models.CharField(blank=True, max_length=200, verbose_name='رمز ورود (هش)')),
                ('security_question', models.CharField(default='اسم گربه\u200cی کوچولوی ما چی بود؟', max_length=200, verbose_name='سؤال امنیتی')),
                ('security_answer_hash', models.CharField(blank=True, max_length=200, verbose_name='پاسخ امنیتی (هش)')),
                ('vault_passcode_hash', models.CharField(blank=True, max_length=200, verbose_name='رمز صندوقچه (هش)')),
                ('boot_logo', models.ImageField(blank=True, upload_to='branding/', verbose_name='لوگوی LoveOS')),
                ('boot_background', models.ImageField(blank=True, upload_to='branding/', verbose_name='پس\u200cزمینه بوت')),
                ('lock_background', models.ImageField(blank=True, upload_to='branding/', verbose_name='پس\u200cزمینه قفل')),
                ('desktop_background_day', models.ImageField(blank=True, upload_to='branding/', verbose_name='پس\u200cزمینه روز')),
                ('desktop_background_night', models.ImageField(blank=True, upload_to='branding/', verbose_name='پس\u200cزمینه شب')),
                ('boot_greeting', models.CharField(default='سلام دخترم. خوش اومدی به دنیای کوچیک بابا.', max_length=200, verbose_name='سلام بوت')),
                ('wrong_pass_message', models.CharField(default='اینو که بابا یادت داده بود دخترم 🥺', max_length=200, verbose_name='پیام رمز اشتباه')),
                ('lock_help_message', models.CharField(default='عزیزم، رمز رو یادت رفت؟ بابا خودش کمکت می\u200cکنه', max_length=255, verbose_name='پیام کمک بابا')),
                ('about_text', models.TextField(blank=True, verbose_name='درباره LoveOS')),
                ('today_message', models.CharField(blank=True, max_length=255, verbose_name='پیام امروز')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English')], default='fa', max_length=2, verbose_name='زبان')),
                ('theme', models.CharField(choices=[('auto', 'خودکار'), ('day', 'روز'), ('night', 'شب')], default='auto', max_length=10, verbose_name='تم')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='صدا')),
                ('font_scale', models.FloatField(default=1.0, verbose_name='اندازه فونت')),
                ('allow_daughter_music_upload', models.BooleanField(default=True, verbose_name='اجازه آپلود موسیقی به دخترم')),
            ],
            options={
                'verbose_name': 'پیکربندی دخترم',
                'verbose_name_plural': '۰۱) پیکربندی دخترم',
            },
        ),
    ]
