# Generated by Django 5.2.17 on 2026-09-14 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('lat', models.FloatField(default=0, verbose_name='عرض جغرافیایی')),
                ('lng', models.FloatField(default=0, verbose_name='طول جغرافیایی')),
                ('accuracy', models.PositiveIntegerField(blank=True, null=True, verbose_name='دقت (متر)')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='شهر')),
                ('timezone', models.CharField(blank=True, max_length=60, verbose_name='منطقه زمانی')),
                ('source', models.CharField(choices=[('device', 'دستگاه دخترم'), ('config', 'پنل بابا')], default='device', max_length=10, verbose_name='منبع')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('is_live', models.BooleanField(default=True, verbose_name='زنده')),
            ],
            options={
                'verbose_name': 'موقعیت زنده',
                'verbose_name_plural': 'موقعیت زنده\u200cی دخترم',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddField(
            model_name='userconfig',
            name='location_auto_sync',
            field=models.BooleanField(default=True, verbose_name='به\u200cروزرسانی خودکار شهر/مختصات پنل از موقعیت واقعی'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='location_city_lookup',
            field=models.BooleanField(default=True, verbose_name='تشخیص خودکار نام شهر از مختصات'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='location_enabled',
            field=models.BooleanField(default=True, verbose_name='استفاده از موقعیت زنده\u200cی دستگاه دخترم'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='location_sync_km',
            field=models.FloatField(default=2.0, verbose_name='حداقل جابجایی برای به\u200cروزرسانی پنل (کیلومتر)'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='location_ttl_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='اعتبار موقعیت زنده (دقیقه)'),
        ),
    ]
