# Generated by Django 5.2.17 on 2026-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_livelocation_userconfig_location_auto_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='search_disabled_sources',
            field=models.JSONField(blank=True, default=list, help_text='کلید منابعی که نمی\u200cخواهی در جستجو دیده شوند؛ مثال: ["easter_eggs", "chat"]', verbose_name='منابع خاموش جستجوی سراسری'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='search_log_enabled',
            field=models.BooleanField(default=False, verbose_name='ثبت عبارت\u200cهای پرجستجو'),
        ),
    ]
