# Generated by Django 5.2.17 on 2026-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userconfig_search_disabled_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='ui_quality',
            field=models.CharField(choices=[('auto', 'خودکار (با تشخیص دستگاه)'), ('lite', 'سبک — مهتاب'), ('balanced', 'متعادل — بلور'), ('dream', 'رویایی — کهکشان')], default='auto', max_length=10, verbose_name='کیفیتِ رابطِ سه\u200cبعدی'),
        ),
    ]
