# Generated by Django 5.2.17 on 2026-09-14 15:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('reminder_minutes', models.PositiveIntegerField(default=30, verbose_name='یادآوری چند دقیقه قبل از تماس')),
                ('notify_on_propose', models.BooleanField(default=True, verbose_name='نوتیف برای پیشنهاد تماس')),
                ('notify_on_answer', models.BooleanField(default=True, verbose_name='نوتیف برای تأیید/رد/جایگزین')),
                ('notify_on_log', models.BooleanField(default=True, verbose_name='نوتیف برای ثبت تماس')),
                ('notify_reminder', models.BooleanField(default=True, verbose_name='یادآوری قبل از تماس')),
                ('default_duration', models.PositiveIntegerField(default=30, verbose_name='مدت پیش\u200cفرض (دقیقه)')),
                ('propose_template', models.CharField(default='دخترم یه تماس پیشنهاد داده ❤', max_length=200, verbose_name='متن نوتیف پیشنهاد تماس')),
                ('approved_template', models.CharField(default='بابا تماس رو قبول کرد ❤', max_length=200, verbose_name='متن نوتیف تأیید')),
                ('rejected_template', models.CharField(default='این ساعت نشد؛ یه زمان دیگه بذاریم', max_length=200, verbose_name='متن نوتیف رد')),
                ('reminder_template', models.CharField(default='الان تماس داریم ❤ {minutes} دقیقه دیگه', max_length=200, verbose_name='متن یادآوری')),
                ('log_template', models.CharField(default='تماس ثبت شد: {minutes} دقیقه', max_length=200, verbose_name='متن ثبت تماس')),
                ('streak_message', models.CharField(default='بابا و دخترم هنوز رکورددار تماس\u200cهای طولانی\u200cاند', max_length=200, verbose_name='پیام رکورد تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات تماس',
                'verbose_name_plural': 'تنظیمات تماس',
            },
        ),
        migrations.CreateModel(
            name='CallAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('proposer', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='پیشنهاددهنده')),
                ('proposee', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='طرف مقابل')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='ساعت')),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='مدت تقریبی (دقیقه)')),
                ('topic', models.CharField(blank=True, max_length=160, verbose_name='موضوع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار جواب'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('rescheduled', 'پیشنهاد جایگزین'), ('done', 'انجام شد'), ('canceled', 'لغو شد')], default='pending', max_length=12, verbose_name='وضعیت')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='پیام همراه')),
                ('answer_note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت جواب')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان جواب')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری فرستاده شد')),
                ('alternative_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternatives', to='calls.callappointment', verbose_name='جایگزین برای')),
            ],
            options={
                'verbose_name': 'تماس هماهنگ\u200cشده',
                'verbose_name_plural': 'تماس\u200cهای هماهنگ\u200cشده',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='CallFreeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='صاحب بازه')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], default=0, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بازه\u200cی آزاد تماس',
                'verbose_name_plural': 'بازه\u200cهای آزاد تماس',
                'ordering': ['owner', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['owner', 'weekday'], name='calls_callf_owner_1a9f27_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ تماس')),
                ('happened_at', models.TimeField(blank=True, null=True, verbose_name='ساعت تماس')),
                ('kind', models.CharField(choices=[('video', 'ویدیویی'), ('voice', 'صوتی'), ('in_person', 'حضوری')], default='video', max_length=12, verbose_name='نوع')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت واقعی (دقیقه)')),
                ('topic', models.CharField(blank=True, max_length=160, verbose_name='موضوع')),
                ('daddy_mood', models.CharField(choices=[('happy', 'خوشحال'), ('normal', 'معمولی'), ('missing', 'دلتنگ')], default='happy', max_length=10, verbose_name='حال بابا')),
                ('daughter_mood', models.CharField(choices=[('happy', 'خوشحال'), ('normal', 'معمولی'), ('missing', 'دلتنگ')], default='happy', max_length=10, verbose_name='حال دخترم')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت کوتاه')),
                ('attachment', models.FileField(blank=True, upload_to='calls/', verbose_name='ضمیمه (ویس/عکس)')),
                ('recorded_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='ثبت\u200cکننده')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='calls.callappointment', verbose_name='تماس')),
            ],
            options={
                'verbose_name': 'ثبت تماس',
                'verbose_name_plural': 'ثبت تماس\u200cها',
                'ordering': ['-happened_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callappointment',
            index=models.Index(fields=['status', 'date'], name='calls_calla_status_80d111_idx'),
        ),
    ]
