# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=140, verbose_name='عنوان')),
                ('level', models.PositiveSmallIntegerField(choices=[(3, '۳×۳ آسان'), (4, '۴×۴ متوسط'), (5, '۵×۵ سخت')], default=3, verbose_name='سطح')),
                ('image', models.ImageField(upload_to='puzzles/', verbose_name='تصویر پازل')),
                ('end_message', models.TextField(default='حلش کردی دخترم ❤', verbose_name='پیام پایان')),
                ('end_voice', models.FileField(blank=True, upload_to='puzzles/', verbose_name='ویس پایان')),
                ('hint_text', models.CharField(default='بابا اومد کمکت ❤', max_length=200, verbose_name='متن راهنما')),
                ('max_hints', models.PositiveSmallIntegerField(default=3, verbose_name='حداکثر راهنما')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پازل',
                'verbose_name_plural': '۲۶) پازل قلب',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('best_time', models.PositiveIntegerField(default=0, verbose_name='بهترین زمان (ثانیه)')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='تعداد بازی')),
                ('completions', models.PositiveIntegerField(default=0, verbose_name='تعداد تکمیل')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='games.puzzle', verbose_name='پازل')),
            ],
            options={
                'verbose_name': 'رکورد پازل',
                'verbose_name_plural': 'پازل — رکوردها',
            },
        ),
    ]
