# Generated by Django 5.2.17 on 2026-09-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamHomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='نام دسته')),
                ('icon', models.CharField(default='🏡', max_length=8, verbose_name='آیکن (ایموجی)')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خانه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای خانه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DreamHomeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام اتاق')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('floor', models.CharField(blank=True, max_length=60, verbose_name='طبقه')),
                ('x', models.FloatField(default=10, verbose_name='موقعیت افقی')),
                ('y', models.FloatField(default=10, verbose_name='موقعیت عمودی')),
                ('w', models.FloatField(default=20, verbose_name='پهنا')),
                ('h', models.FloatField(default=20, verbose_name='ارتفاع')),
                ('color', models.CharField(default='#f9a8d4', max_length=20, verbose_name='رنگ')),
                ('icon', models.CharField(default='🛋', max_length=8, verbose_name='آیکن (ایموجی)')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='افزوده\u200cشده توسط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'اتاق خانه\u200cی رویایی',
                'verbose_name_plural': 'اتاق\u200cهای خانه\u200cی رویایی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DreamHomeInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('photo', models.ImageField(upload_to='dreamhome/inspiration/', verbose_name='عکس')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('uploaded_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='آپلود شده توسط')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations', to='dreamhome.dreamhomecategory', verbose_name='دسته')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations', to='dreamhome.dreamhomeroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'عکس الهام',
                'verbose_name_plural': 'گالری الهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamHomeRoomIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('idea', 'ایده'), ('color', 'رنگ'), ('furniture', 'مبلمان'), ('decor', 'دکور')], default='idea', max_length=12, verbose_name='نوع')),
                ('text', models.CharField(max_length=255, verbose_name='متن')),
                ('color_value', models.CharField(blank=True, max_length=20, verbose_name='کد رنگ')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='افزوده\u200cشده توسط')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='dreamhome.dreamhomeroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'ایده\u200cی اتاق',
                'verbose_name_plural': 'ایده\u200cهای اتاق\u200cبه\u200cاتاق',
                'ordering': ['kind', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspirationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='نویسنده')),
                ('text', models.CharField(max_length=500, verbose_name='متن')),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dreamhome.dreamhomeinspiration', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'کامنت الهام',
                'verbose_name_plural': 'کامنت\u200cهای الهام',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamHomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان ویژگی')),
                ('importance', models.CharField(choices=[('must', 'ضروری'), ('nice', 'خوبه داشته باشیم'), ('luxury', 'لوکس')], default='must', max_length=10, verbose_name='اهمیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('photo', models.ImageField(blank=True, upload_to='dreamhome/features/', verbose_name='عکس نمونه')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='افزوده\u200cشده توسط')),
                ('is_done', models.BooleanField(default=False, verbose_name='تیک خورده (قطعی شد)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='dreamhome.dreamhomecategory', verbose_name='دسته')),
                ('linked_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_features', to='content.futureplan', verbose_name='لینک به آرزوی ما')),
            ],
            options={
                'verbose_name': 'ویژگی خانه\u200cی رویایی',
                'verbose_name_plural': '۲۸) ویژگی\u200cهای خانه\u200cی رویایی',
                'ordering': ['importance', 'order', '-created_at'],
                'indexes': [models.Index(fields=['importance'], name='dreamhome_d_importa_f1af29_idx')],
            },
        ),
    ]
