# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('film', 'فیلم'), ('series', 'سریال')], default='film', max_length=10, verbose_name='نوع')),
                ('link', models.URLField(blank=True, verbose_name='لینک تماشا')),
                ('status', models.CharField(choices=[('todo', 'ندیدم'), ('watching', 'در حال تماشا'), ('done', 'دیدم')], default='todo', max_length=10, verbose_name='وضعیت')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز (۱-۵ قلب)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('poster', models.ImageField(blank=True, upload_to='cinema/', verbose_name='پوستر')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='اضافه شده توسط')),
            ],
            options={
                'verbose_name': 'فیلم/سریال',
                'verbose_name_plural': '۰۹) سینمای ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('letter', models.CharField(max_length=2, verbose_name='حرف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('message', models.TextField(blank=True, verbose_name='پیام ستاره مرکزی')),
                ('stars', models.JSONField(blank=True, default=list, verbose_name='ستاره\u200cها [[x,y],...]')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'صورت فلکی',
                'verbose_name_plural': '۰۸) آسمان ستاره\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('target', models.DateTimeField(verbose_name='تاریخ هدف')),
                ('icon', models.CharField(default='heart', max_length=40, verbose_name='آیکن')),
                ('done_message', models.CharField(default='رسیدیم دخترم! 🎉', max_length=255, verbose_name='پیام رسیدن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شمارش معکوس',
                'verbose_name_plural': '۰۶) شمارش معکوس\u200cها',
                'ordering': ['target'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=80, verbose_name='اسم گل')),
                ('color', models.CharField(default='#f9a8d4', max_length=20, verbose_name='رنگ')),
                ('emoji', models.CharField(default='🌸', max_length=8, verbose_name='شکل')),
                ('water_count', models.PositiveIntegerField(default=0, verbose_name='تعداد آب دادن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'گل باغچه',
                'verbose_name_plural': '۰۷) باغچه\u200cی ما',
            },
        ),
        migrations.CreateModel(
            name='FlowerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='پیام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پیام شکوفه',
                'verbose_name_plural': 'پیام\u200cهای شکوفه',
            },
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('travel', 'سفر'), ('work', 'کار'), ('wish', 'آرزو'), ('home', 'خانه')], default='wish', max_length=10, verbose_name='دسته')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام شد')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='توسط')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'آرزو',
                'verbose_name_plural': '۱۱) آرزوهای ما',
                'ordering': ['is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن نامه')),
                ('open_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان باز شدن')),
                ('is_opened', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': '۰۵) نامه\u200cهای نجوا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('mood', models.CharField(max_length=12, verbose_name='حال')),
            ],
            options={
                'verbose_name': 'ثبت حال',
                'verbose_name_plural': 'ثبت حال\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('question', models.CharField(max_length=255, verbose_name='سؤال')),
                ('option_a', models.CharField(max_length=140, verbose_name='گزینه ۱')),
                ('option_b', models.CharField(max_length=140, verbose_name='گزینه ۲')),
                ('option_c', models.CharField(blank=True, max_length=140, verbose_name='گزینه ۳')),
                ('option_d', models.CharField(blank=True, max_length=140, verbose_name='گزینه ۴')),
                ('correct', models.CharField(choices=[('a', '۱'), ('b', '۲'), ('c', '۳'), ('d', '۴')], default='a', max_length=1, verbose_name='پاسخ درست')),
                ('explanation', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سؤال کوییز',
                'verbose_name_plural': '۱۰) کوییز ما',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='کل')),
            ],
            options={
                'verbose_name': 'نتیجه کوییز',
                'verbose_name_plural': 'نتایج کوییز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='نمره\u200cی کاملت رو گرفتی دخترم ❤ تو منو از خودم بهتر بلدی.', verbose_name='پیام نمره کامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'جایزه کوییز',
                'verbose_name_plural': 'جایزه کوییز',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=140, verbose_name='عنوان')),
                ('artist', models.CharField(blank=True, max_length=140, verbose_name='خواننده')),
                ('audio', models.FileField(upload_to='songs/', verbose_name='فایل آهنگ')),
                ('cover', models.ImageField(blank=True, upload_to='songs/covers/', verbose_name='کاور')),
                ('is_main', models.BooleanField(default=False, verbose_name='آهنگ اصلی ما')),
                ('why_this_song', models.TextField(blank=True, verbose_name='چرا این آهنگ؟')),
                ('lyrics', models.TextField(blank=True, verbose_name='متن آهنگ')),
                ('uploaded_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='آپلود توسط')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': '۰۳) موسیقی ما',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('command', models.CharField(max_length=80, unique=True, verbose_name='دستور')),
                ('output', models.TextField(verbose_name='خروجی')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='توضیح در help')),
                ('hidden', models.BooleanField(default=False, verbose_name='مخفی از help')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دستور ترمینال',
                'verbose_name_plural': '۱۴) دستورهای ترمینال',
                'ordering': ['command'],
            },
        ),
        migrations.CreateModel(
            name='TutorialChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('key', models.SlugField(max_length=40, unique=True, verbose_name='کلید (اسم اپ)')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن درس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درس آموزش',
                'verbose_name_plural': '۱۵) آموزش سیستم\u200cعامل',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('video', 'ویدیو'), ('audio', 'صدا'), ('image', 'عکس'), ('text', 'متن')], default='text', max_length=10, verbose_name='نوع')),
                ('file', models.FileField(blank=True, upload_to='vault/', verbose_name='فایل')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'محتوای صندوقچه',
                'verbose_name_plural': '۱۳) صندوقچه\u200cی خصوصی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('morning', 'صبح\u200cها'), ('night', 'شب\u200cها'), ('missing', 'وقتی دلت تنگه'), ('happy', 'وقتی خوشحالی'), ('sad', 'وقتی ناراحتی'), ('sleepless', 'وقتی نمی\u200cتونی بخوابی'), ('random', 'تصادفی')], default='random', max_length=20, verbose_name='دسته')),
                ('audio', models.FileField(upload_to='voices/', verbose_name='فایل صدا')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت بابا')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='مدت (ثانیه)')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پخش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویس بابا',
                'verbose_name_plural': '۰۲) صندوق صدای بابا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('mood', models.CharField(choices=[('happy', 'خوشحال'), ('missing', 'دلتنگ'), ('tired', 'خسته'), ('sad', 'ناراحت'), ('excited', 'پر انرژی'), ('sleepy', 'خواب\u200cآلود')], max_length=12, unique=True, verbose_name='حال')),
                ('message', models.TextField(verbose_name='پیام بابا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.voice', verbose_name='ویس')),
            ],
            options={
                'verbose_name': 'پیام حال دل',
                'verbose_name_plural': '۱۲) پیام\u200cهای حال دل',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن خاطره')),
                ('photo', models.ImageField(blank=True, upload_to='memories/', verbose_name='عکس')),
                ('happened_on', models.DateField(blank=True, null=True, verbose_name='تاریخ')),
                ('place', models.CharField(blank=True, max_length=140, verbose_name='مکان')),
                ('is_future', models.BooleanField(default=False, verbose_name='خاطره\u200cی آینده (قفل)')),
                ('unlock_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان باز شدن')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='باز شده')),
                ('locked_text', models.CharField(default='این خاطره هنوز نوشته نشده...', max_length=200, verbose_name='متن حالت قفل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.voice', verbose_name='ویس همراه')),
            ],
            options={
                'verbose_name': 'خاطره',
                'verbose_name_plural': '۰۴) خاطره\u200cها و رؤیاها',
                'ordering': ['-happened_on', '-created_at'],
            },
        ),
    ]
