# Generated by Django 5.2.17 on 2026-09-16 09:35
"""
۰۰۰۲ — افزودنِ «نوع» به صورت‌های فلکی + ساختنِ دو شکلِ آسمان (♥ و ∞)

دو کار در یک مایگریشن:
  ۱) فیلد ``kind`` (حرفِ اسم / شکلِ آسمان) تا فرانت بتواند آن‌ها را در دو
     منطقه‌ی جدا نمایش دهد.
  ۲) یک مایگریشنِ داده که ♥ و ∞ را می‌سازد.

چرا شکل‌ها در مایگریشن‌اند و نه فقط در seed؟
  چون دیتابیسِ زنده‌ی بابا از قبل seed شده و او لزوماً seed را دوباره اجرا
  نمی‌کند. مایگریشن تضمین می‌کند بعد از ``manage.py migrate`` روی هاست،
  این دو شکل **حتماً** در آسمان باشند. seed هم همین‌ها را idempotent دارد تا
  نصبِ تازه یا seedِ دوباره چیزی را خراب نکند.

چرا عددِ ستاره‌ها این‌جا «یخ‌زده» (literal) است و نه import از
``content.constellations``؟
  چون مایگریشن یک سندِ تاریخی است: اگر روزی هندسه‌ی آن ماژول عوض شود، اجرای
  مایگریشنِ قدیمی نباید رفتار متفاوتی پیدا کند. این دقیقاً همان چیزی است که
  مستندات جنگو توصیه می‌کند. ``content/constellations.py`` منبعِ زنده برای
  seed و کاربردهای آینده است و همین عدد را تولید می‌کند.

ایمنی:
  • idempotent — با ``filter(letter=...)`` چک می‌شود، پس اجرای دوباره بی‌اثر است
  • بدون SQL خام — روی SQLite و MySQL یکسان کار می‌کند
  • برگشت‌پذیر — ``reverse_code`` شکل‌ها را پاک می‌کند
  • order از ۹۰ شروع می‌شود تا با حرف‌های اسم (که از ۰ شماره می‌خورند) هرگز
    برخورد نکند
"""
from django.db import migrations, models

# ---------------------------------------------------------------- ♥ قلب ---
# منحنیِ کلاسیکِ قلب: x = 16·sin³t , y = 13cos t − 5cos 2t − 2cos 3t − cos 4t
# ۱۷ نقطه (۱۶ بازه + تکرارِ نقطه‌ی اول تا حلقه بسته شود). y رو به بالا.
HEART_STARS = [
    [0.5, 0.769], [0.528, 0.864], [0.677, 1.0], [0.894, 0.956], [1.0, 0.734],
    [0.894, 0.479], [0.677, 0.258], [0.528, 0.078], [0.5, 0.0], [0.472, 0.078],
    [0.323, 0.258], [0.106, 0.479], [0.0, 0.734], [0.106, 0.956], [0.323, 1.0],
    [0.472, 0.864], [0.5, 0.769],
]

# ----------------------------------------------------------- ∞ بی‌نهایت ---
# لمینیسکاتِ برنولی: x = cos t/(1+sin²t) , y = sin t·cos t/(1+sin²t)
# ۲۱ نقطه؛ یک دورِ کامل، کلِ هشت را یک بار می‌پیماید و در مرکز گره می‌خورد.
INFINITY_STARS = [
    [1.0, 0.5], [0.934, 0.88], [0.801, 1.0], [0.678, 0.907], [0.581, 0.718],
    [0.5, 0.5], [0.419, 0.282], [0.322, 0.093], [0.199, 0.0], [0.066, 0.12],
    [0.0, 0.5], [0.066, 0.88], [0.199, 1.0], [0.322, 0.907], [0.419, 0.718],
    [0.5, 0.5], [0.581, 0.282], [0.678, 0.093], [0.801, 0.0], [0.934, 0.12],
    [1.0, 0.5],
]

SHAPES = [
    {
        "letter": "♥",
        "order": 90,
        "message": (
            "این قلب رو با ستاره‌ها کشیدم، چون هر ستاره‌اش یه روزیه که "
            "دوستت داشتم. هیچ‌وقت خاموش نمی‌شه."
        ),
        "stars": HEART_STARS,
    },
    {
        "letter": "∞",
        "order": 91,
        "message": (
            "بی‌نهایت یعنی هر چقدر هم دور باشیم، عشقِ ما ته نداره. "
            "این علامت رو گذاشتم این‌جا که یادت بمونه: فاصله فقط یه عدده."
        ),
        "stars": INFINITY_STARS,
    },
]


def add_sky_shapes(apps, schema_editor):
    """♥ و ∞ را می‌سازد؛ اگر از قبل باشند دستشان نمی‌زند (idempotent)."""
    Constellation = apps.get_model("content", "Constellation")
    for shape in SHAPES:
        if Constellation.objects.filter(letter=shape["letter"], kind="shape").exists():
            continue
        Constellation.objects.create(kind="shape", is_active=True, **shape)


def remove_sky_shapes(apps, schema_editor):
    """برگشت: فقط شکل‌ها را پاک می‌کند، حرف‌های اسم دخترم دست‌نخورده."""
    Constellation = apps.get_model("content", "Constellation")
    Constellation.objects.filter(kind="shape", letter__in=[s["letter"] for s in SHAPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='kind',
            field=models.CharField(choices=[('letter', 'حرفِ اسم'), ('shape', 'شکلِ آسمان')], db_index=True, default='letter', max_length=8, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='letter',
            field=models.CharField(help_text='برای شکل\u200cها: ♥ یا ∞', max_length=2, verbose_name='حرف / نماد'),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='stars',
            field=models.JSONField(blank=True, default=list, help_text='مختصات نسبی ۰..۱ با y رو به بالا', verbose_name='ستاره\u200cها [[x,y],...]'),
        ),
        migrations.RunPython(add_sky_shapes, remove_sky_shapes),
    ]
