# Generated by Django 5.2.17 on 2026-09-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='نویسنده')),
                ('cover', models.ImageField(blank=True, upload_to='reading/covers/', verbose_name='جلد')),
                ('status', models.CharField(choices=[('reading', 'الان داریم می\u200cخونیم'), ('finished', 'خوندیم'), ('want', 'می\u200cخوایم بخونیم')], default='want', max_length=10, verbose_name='وضعیت')),
                ('summary', models.TextField(blank=True, verbose_name='چکیده')),
                ('why_this_book', models.CharField(blank=True, max_length=255, verbose_name='چرا این کتاب؟')),
                ('pdf', models.FileField(blank=True, upload_to='reading/pdf/', verbose_name='فایل PDF')),
                ('link', models.URLField(blank=True, verbose_name='لینک (نسخه\u200cی آنلاین)')),
                ('is_physical', models.BooleanField(default=False, verbose_name='کتاب کاغذی داریم')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='تعداد فصل')),
                ('added_by', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daddy', max_length=10, verbose_name='اضافه شده توسط')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='شروع')),
                ('finished_on', models.DateField(blank=True, null=True, verbose_name='تمام شد در')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('library_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_entries', to='library.book', verbose_name='کتاب کتابخانه')),
            ],
            options={
                'verbose_name': 'کتاب مشترک',
                'verbose_name_plural': '۲۷) کتاب\u200cهای مشترک',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='شماره فصل')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان فصل')),
                ('text', models.TextField(blank=True, verbose_name='متن (اختیاری)')),
                ('page_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='از صفحه')),
                ('page_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='تا صفحه')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reading.readingbook', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'فصل کتاب مشترک',
                'verbose_name_plural': 'فصل\u200cهای کتاب مشترک',
                'ordering': ['book', 'order'],
                'unique_together': {('book', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='نویسنده')),
                ('text', models.TextField(verbose_name='پیام')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='reading.chaptercomment', verbose_name='پاسخ به')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reading.readingchapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'پیام فصل',
                'verbose_name_plural': 'گفتگوی فصل\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='نویسنده')),
                ('text', models.TextField(verbose_name='یادداشت')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='امتیاز (۱-۵ قلب)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='این فصل را خواندم')),
                ('page_hint', models.CharField(blank=True, max_length=20, verbose_name='نزدیک صفحه\u200cی')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reading.readingbook', verbose_name='کتاب')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reading.readingchapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'یادداشت فصل',
                'verbose_name_plural': 'یادداشت\u200cهای فصل',
                'ordering': ['chapter__order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='ثبت\u200cکننده')),
                ('text', models.TextField(verbose_name='متن نقل\u200cقول')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='چرا این جمله؟')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='reading.readingbook', verbose_name='کتاب')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='reading.readingchapter', verbose_name='فصل')),
            ],
            options={
                'verbose_name': 'نقل\u200cقول کتاب',
                'verbose_name_plural': '۲۷) نقل\u200cقول\u200cهای محبوب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.CharField(choices=[('daddy', 'بابا'), ('daughter', 'دخترم')], default='daughter', max_length=10, verbose_name='کاربر')),
                ('current_chapter', models.PositiveIntegerField(default=1, verbose_name='فصل جاری')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد')),
                ('updated_note', models.CharField(blank=True, max_length=200, verbose_name='آخرین یادداشت')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='reading.readingbook', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'پیشرفت کتاب\u200cخوانی',
                'verbose_name_plural': 'پیشرفت کتاب\u200cخوانی',
                'ordering': ['book', 'owner'],
                'unique_together': {('owner', 'book')},
            },
        ),
    ]
