# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('sender', models.CharField(choices=[('daughter', 'دخترم'), ('daddy', 'بابا')], max_length=10, verbose_name='فرستنده')),
                ('text', models.TextField(verbose_name='متن')),
                ('via', models.CharField(default='app', max_length=20, verbose_name='از طریق')),
                ('soroush_message_id', models.CharField(blank=True, max_length=64, verbose_name='شناسه پیام سروش')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': '۲۰) چت با بابا',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('direction', models.CharField(choices=[('daddy_to_daughter', 'بابا ← دخترم'), ('daughter_to_daddy', 'دخترم ← بابا')], max_length=20, verbose_name='جهت')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='پیام بغل')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شد')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دیدن')),
            ],
            options={
                'verbose_name': 'بغل',
                'verbose_name_plural': '۲۱) بغل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HugSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_title', models.CharField(default='بابا داره بغلت می\u200cکنه...', max_length=140, verbose_name='عنوان اعلان ورودی')),
                ('incoming_message', models.CharField(default='بابا الان بغلت کرد.', max_length=255, verbose_name='پیام بعد از باز کردن')),
                ('outgoing_message', models.CharField(default='دخترت الان بغلت کرد ❤', max_length=255, verbose_name='پیام سروش به بابا')),
                ('vibration_pattern', models.CharField(default='200,100,100,100,100,100,200', max_length=120, verbose_name='الگوی ویبره (میلی\u200cثانیه، با کاما)')),
                ('warm_color', models.CharField(default='#ffd6a5', max_length=20, verbose_name='رنگ گرم پس\u200cزمینه')),
                ('heartbeat_sound', models.FileField(blank=True, upload_to='hug/', verbose_name='صدای ضربان')),
            ],
            options={
                'verbose_name': 'تنظیمات بغل',
                'verbose_name_plural': 'تنظیمات بغل',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('rtype', models.CharField(choices=[('manual', 'دستی'), ('weather_rain', 'باران'), ('weather_snow', 'برف'), ('weather_hot', 'گرما'), ('weather_cold', 'سرما'), ('cycle_before', '۲ روز قبل پریود'), ('cycle_start', 'روز اول پریود'), ('anniversary', 'سالگرد'), ('birthday', 'تولد'), ('random', 'تصادفی')], default='manual', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=140, verbose_name='عنوان')),
                ('text', models.CharField(max_length=255, verbose_name='متن')),
                ('when', models.DateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('repeat', models.CharField(choices=[('once', 'یک\u200cبار'), ('every_n', 'هر N روز')], default='once', max_length=10, verbose_name='تکرار')),
                ('repeat_days', models.PositiveIntegerField(default=0, verbose_name='هر چند روز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('muted_by_daughter', models.BooleanField(default=False, verbose_name='بی\u200cصدا شده توسط دخترم')),
            ],
            options={
                'verbose_name': 'یادآور مهربان',
                'verbose_name_plural': '۲۲) یادآورهای مهربان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دیدن')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='social.reminder')),
            ],
            options={
                'verbose_name': 'لاگ یادآور',
                'verbose_name_plural': 'لاگ یادآورها',
                'ordering': ['-sent_at'],
            },
        ),
    ]
