# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('icon', models.CharField(default='star', max_length=40, verbose_name='آیکن')),
                ('secret_message', models.TextField(blank=True, verbose_name='پیام مخفی بابا')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='آستانه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': '۱۶) دستاوردها',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('action', models.CharField(max_length=80, verbose_name='فعالیت')),
                ('app', models.CharField(blank=True, max_length=40, verbose_name='اپ')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='جزئیات')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='داده')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': '۱۹) لاگ فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True, verbose_name='کلید')),
                ('value', models.IntegerField(default=0, verbose_name='مقدار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EasterEgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('trigger_type', models.CharField(choices=[('click_logo_5', '۵ بار کلیک روی لوگو'), ('type_love', 'تایپ کلمه love'), ('konami', 'کد کونامی'), ('terminal_rm', 'ترمینال: sudo rm -rf /loneliness'), ('terminal_sandwich', 'ترمینال: sudo make me a sandwich'), ('midnight', 'ساعت ۰۰:۰۰ تا ۰۵:۰۰'), ('birthday', 'روز تولد دخترم'), ('anniversary', 'سالگرد ما'), ('map_zoom', 'زوم روی خانه بابا'), ('star_double_click', 'دوبار کلیک روی ستاره مرکزی'), ('garden_5_water', '۵ بار آب دادن به یک گل'), ('hug_3', '۳ بار پشت\u200cسرهم بغل کردن بابا'), ('chat_love', 'نوشتن «دوستت دارم» در چت'), ('music_3_play', '۳ بار پخش آهنگ اصلی'), ('lock_5_wrong', '۵ رمز اشتباه'), ('custom', 'دلخواه')], max_length=30, unique=True, verbose_name='نوع تریگر')),
                ('message', models.TextField(verbose_name='پیام')),
                ('attachment', models.FileField(blank=True, upload_to='eggs/', verbose_name='پیوست (صدا/عکس/ویدیو)')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='تنظیم اضافه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'راز مخفی',
                'verbose_name_plural': '۲۴) رازهای مخفی',
                'ordering': ['trigger_type'],
            },
        ),
        migrations.CreateModel(
            name='OSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('daddy', 'پیام بابا'), ('achievement', 'دستاورد'), ('chat', 'چت'), ('memory', 'خاطره باز شد'), ('reminder', 'یادآور مهربان'), ('hug', 'بغل'), ('med', 'دارو'), ('book', 'کتاب'), ('easter', 'راز'), ('system', 'سیستم')], default='daddy', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, verbose_name='متن')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='آیکن')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='داده اضافه')),
                ('action_app', models.CharField(blank=True, max_length=40, verbose_name='باز کردن اپ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اعلان سیستم',
                'verbose_name_plural': '۱۷) اعلان\u200cهای سیستم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoroushOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('event', models.CharField(max_length=60, verbose_name='رویداد')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='chat_id')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال شد'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('tries', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ سرور')),
            ],
            options={
                'verbose_name': 'پیام سروش',
                'verbose_name_plural': '۱۸) صندوق خروجی سروش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شده')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='core.achievement')),
            ],
            options={
                'verbose_name': 'دستاورد باز شده',
                'verbose_name_plural': 'دستاوردهای باز شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EasterEggLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان کشف')),
                ('egg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.easteregg')),
            ],
            options={
                'verbose_name': 'کشف راز',
                'verbose_name_plural': 'کشف رازها',
                'ordering': ['-activated_at'],
            },
        ),
    ]
