# Generated by Django 5.2.17 on 2026-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osnotification',
            name='kind',
            field=models.CharField(choices=[('daddy', 'پیام بابا'), ('achievement', 'دستاورد'), ('chat', 'چت'), ('memory', 'خاطره باز شد'), ('reminder', 'یادآور مهربان'), ('hug', 'بغل'), ('med', 'دارو'), ('book', 'کتاب'), ('easter', 'راز'), ('system', 'سیستم'), ('call', 'تماس'), ('gift', 'هدیه'), ('home', 'خانه\u200cی رویایی'), ('language', 'پل زبان')], default='daddy', max_length=20, verbose_name='نوع'),
        ),
        migrations.AddConstraint(
            model_name='achievementunlock',
            constraint=models.UniqueConstraint(fields=('achievement',), name='unique_achievement_unlock'),
        ),
    ]
