# Generated by Django 5.2.17 on 2026-09-14 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('text', models.CharField(max_length=200, verbose_name='متن')),
                ('hour', models.PositiveSmallIntegerField(default=10, verbose_name='ساعت')),
                ('minute', models.PositiveSmallIntegerField(default=0, verbose_name='دقیقه')),
                ('enabled', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'یادآور مراقبتی',
                'verbose_name_plural': 'چرخه و مراقبت — مراقبت از خود',
                'ordering': ['hour', 'minute'],
            },
        ),
        migrations.CreateModel(
            name='CycleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'دوره پریود',
                'verbose_name_plural': '۲۳) چرخه و مراقبت — دوره\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('who', models.CharField(default='daddy', max_length=40, verbose_name='چه کسی')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'لاگ دسترسی سلامت',
                'verbose_name_plural': 'چرخه و مراقبت — لاگ دسترسی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=140, verbose_name='اسم دارو')),
                ('dose', models.CharField(blank=True, max_length=80, verbose_name='دوز')),
                ('pills_per_time', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد در هر نوبت')),
                ('times', models.JSONField(default=list, verbose_name='ساعت\u200cهای مصرف (مثلاً 08:00 و 20:00)')),
                ('duration', models.CharField(choices=[('7', '۷ روزه'), ('30', '۳۰ روزه'), ('ongoing', 'همیشگی')], default='ongoing', max_length=10, verbose_name='مدت')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='شروع')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت (مثلاً بعد از غذا)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'چرخه و مراقبت — داروها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('day', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='تاریخ')),
                ('mood', models.CharField(blank=True, choices=[('good', 'خوب'), ('ok', 'معمولی'), ('bad', 'بد')], max_length=6, verbose_name='حال')),
                ('energy', models.CharField(blank=True, choices=[('high', 'زیاد'), ('mid', 'متوسط'), ('low', 'کم')], max_length=6, verbose_name='انرژی')),
                ('headache', models.BooleanField(default=False, verbose_name='سردرد')),
                ('backache', models.BooleanField(default=False, verbose_name='کمردرد')),
                ('stomachache', models.BooleanField(default=False, verbose_name='دل\u200cدرد')),
                ('nausea', models.BooleanField(default=False, verbose_name='حالت تهوع')),
                ('sleep', models.CharField(blank=True, choices=[('good', 'خوب'), ('bad', 'بد')], max_length=6, verbose_name='خواب')),
                ('appetite', models.CharField(blank=True, choices=[('high', 'زیاد'), ('normal', 'معمولی'), ('low', 'کم')], max_length=8, verbose_name='اشتها')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'علائم روزانه',
                'verbose_name_plural': 'چرخه و مراقبت — علائم',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('scheduled_for', models.DateTimeField(verbose_name='زمان برنامه\u200cریزی')),
                ('status', models.CharField(choices=[('taken', 'خوردم'), ('snoozed', 'بعداً'), ('skipped', 'نمی\u200cتونم بخورم'), ('pending', 'منتظر')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اقدام')),
                ('snooze_until', models.DateTimeField(blank=True, null=True, verbose_name='یادآوری مجدد')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='health.medication')),
            ],
            options={
                'verbose_name': 'لاگ دارو',
                'verbose_name_plural': 'چرخه و مراقبت — لاگ داروها',
                'ordering': ['-scheduled_for'],
                'unique_together': {('medication', 'scheduled_for')},
            },
        ),
    ]
